In [57]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.preprocessing.sequence import TimeseriesGenerator


In [58]:
# Some Sequence 
s1=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
s2=[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
s3=[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150]
s4=[4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196, 200]
s5=[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250]
s6=[6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 120, 126, 132, 138, 144, 150, 156, 162, 168, 174, 180, 186, 192, 198, 204, 210, 216, 222, 228, 234, 240, 246, 252, 258, 264, 270, 276, 282, 288, 294, 300]
s7=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500]
s8=[15, 25, 35, 45, 55, 65, 75, 85, 95, 105, 115, 125, 135, 145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255, 265, 275, 285, 295, 305, 315, 325, 335, 345, 355, 365, 375, 385, 395, 405, 415, 425, 435, 445, 455, 465, 475, 485, 495, 505, 515]
s9=[25, 50, 75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325, 350, 375, 400, 425, 450, 475, 500, 525, 550, 575, 600, 625, 650, 675, 700, 725, 750, 775, 800, 825, 850, 875, 900, 925, 950, 975, 1000, 1025, 1050, 1075, 1100, 1125, 1150, 1175, 1200, 1225.1250]
s10=[20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640, 660, 680, 700, 720, 740, 760, 780, 800, 820, 840, 860, 880, 900, 920, 940, 960, 980, 1000]
s11=[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101]
s12=[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100, 103, 106, 109, 112, 115, 118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148, 151, 154, 157, 160, 163, 166, 169]
s13=[11, 21, 31, 41, 51, 61, 71, 81, 91, 101, 111, 121, 131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251, 261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381, 391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491, 501, 511]


In [59]:
data=[s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13]


In [60]:
# [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
# [1,2,3,4,5]->6
# [2,3,4,5,6]->7
# [3,4,5,6,7]->8

# To generate data in the above Sequence Let's wrie a function 

def Sequence_generator(seq,n_steps):
  X=[]
  Y=[]
  for s in data:
    for i in range(len(s)):
      last_index=i+n_steps
      if last_index>len(s)-1:
        break
      seq_x,seq_y= s[i:last_index],s[last_index]
      X.append(seq_x)
      Y.append(seq_y)
  X=np.array(X)
  Y=np.array(Y)
  return X,Y

In [61]:
n_steps=5
X,Y=Sequence_generator(data,n_steps)

In [62]:
X

array([[  1,   2,   3,   4,   5],
       [  2,   3,   4,   5,   6],
       [  3,   4,   5,   6,   7],
       ...,
       [441, 451, 461, 471, 481],
       [451, 461, 471, 481, 491],
       [461, 471, 481, 491, 501]])

In [63]:
import tensorflow as tf
from tensorflow import keras

In [64]:
# define Your Model 

model = tf.keras.Sequential()
model.add(keras.layers.LSTM(512, input_shape=(n_steps, 1)))
model.add(keras.layers.Dense(256))
model.add(keras.layers.Dense(128))
model.add(keras.layers.Dense(1))
model.compile(optimizer="adam",loss="mse")

In [65]:

X.shape

(594, 5)

In [66]:
# we have to reshape our data According to model 
X=X.reshape(X.shape[0],X.shape[1],1)

In [67]:
X.shape

(594, 5, 1)

In [68]:
# after Reshaping 

print(X[:2])

[[[1]
  [2]
  [3]
  [4]
  [5]]

 [[2]
  [3]
  [4]
  [5]
  [6]]]


In [69]:
# trined model for 1000 epochs 
# for better performance shuffled the dataset 

history=model.fit(X, Y,shuffle=True ,epochs=1000)

Epoch 1/1000
19/19 [==============================] - 3s 65ms/step - loss: 73986.2500
Epoch 2/1000
19/19 [==============================] - 1s 64ms/step - loss: 9023.7529
Epoch 3/1000
19/19 [==============================] - 1s 64ms/step - loss: 1139.5415
Epoch 4/1000
19/19 [==============================] - 1s 63ms/step - loss: 430.7594
Epoch 5/1000
19/19 [==============================] - 1s 62ms/step - loss: 163.4041
Epoch 6/1000
19/19 [==============================] - 1s 59ms/step - loss: 171.3729
Epoch 7/1000
19/19 [==============================] - 1s 60ms/step - loss: 197.3699
Epoch 8/1000
19/19 [==============================] - 1s 62ms/step - loss: 96.0440
Epoch 9/1000
19/19 [==============================] - 1s 65ms/step - loss: 60.0733
Epoch 10/1000
19/19 [==============================] - 1s 60ms/step - loss: 239.0499
Epoch 11/1000
19/19 [==============================] - 1s 61ms/step - loss: 154.4879
Epoch 12/1000
19/19 [==============================] - 1s 61ms/step - lo

In [79]:
x_input = np.array([35,70,105,140,175]).reshape((1,5,1))
x_input

array([[[ 35],
        [ 70],
        [105],
        [140],
        [175]]])

In [83]:
yhat = model.predict(x_input, verbose=1)
yhat=yhat.round()
print(yhat[0][0])

1/1 [==============================] - 0s 32ms/step
212.0


In [ ]:
model.save('/content/drive/MyDrive/dataset/counting numbers/models1.h5')